project:
  type: website
  output-dir: docs
  resources: 
    - CNAME
website:
  title: "Becoming A Forehanded Sailor"
  favicon: anchor.png
  navbar:
    logo: anchor.png
    search: true
    left:
      - href: index.qmd
        text: Home
      - text: "Outlier"
        menu: 
          - outlier.qmd
          - motor.qmd
      - text: "Boats and Stuff"
        menu: 
          - boats.qmd
          - dinghies.qmd
      - href: boats.qmd
      - text: "Seamanship"
        menu:
          - seamanship.qmd
          - navigation.qmd
          - weather.qmd
          - mooring.qmd
      - videos.qmd
      - text: "Captain's Log"
        menu: 
          - caplog2021.qmd
          - caplog2022.qmd
          - caplog2023.qmd
      - about.qmd

format:
  html:
    theme:  lumen # zephyr, yeti, superhero, sketchy, lumen, materia, sandstone
    css: styles.css
    toc: true



