project:
  type: website
  output-dir: docs
website:
  title: "Becoming A Forehanded Sailor"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: boat_projects.qmd
      - resources.qmd
      - videos.qmd

format:
  html:
    theme:  lumen # zephyr, yeti, superhero, sketchy, lumen, materia, sandstone
    css: styles.css
    toc: true



