project:
  type: website
  output-dir: docs
  
website:
  title: "Becoming A Forehanded Sailor"
  favicon: anchor.png
  navbar:
    logo: anchor.png
    search: true
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: boat_projects.qmd
      - text: "Resources"
        menu:
          - resources.qmd
          - navigation.qmd
          - weather.qmd
          - mooring.qmd
      - videos.qmd

format:
  html:
    theme:  lumen # zephyr, yeti, superhero, sketchy, lumen, materia, sandstone
    css: styles.css
    toc: true



