project:
  type: website

website:
  title: "Becoming A Forehanded Sailor"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:  lumen # zephyr, yeti, superhero, sketchy, lumen, materia, sandstone
    css: styles.css
    toc: true



